action_id: trunk-share-with-everyone
date: 2023-12-12 03:52:37
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1702353157
full_timestamp:
  nanos: 514058000
  seconds: 1702353157
trunk_version: 1.18.0
